In [33]:
import pandas as pd

In [42]:
train = pd.read_csv('./CSV/train.csv')

train.tail(20)

                     site_id  year   volume
2157  owyhee_r_bl_owyhee_dam  1994   72.891
2158  owyhee_r_bl_owyhee_dam  1995  454.189
2159  owyhee_r_bl_owyhee_dam  1996  412.222
2160  owyhee_r_bl_owyhee_dam  1997  410.556
2161  owyhee_r_bl_owyhee_dam  1998  683.764
2162  owyhee_r_bl_owyhee_dam  1999  371.472
2163  owyhee_r_bl_owyhee_dam  2000  176.237
2164  owyhee_r_bl_owyhee_dam  2001  140.703
2165  owyhee_r_bl_owyhee_dam  2002  280.103
2166  owyhee_r_bl_owyhee_dam  2003  134.794
2167  owyhee_r_bl_owyhee_dam  2004  184.896
2168  owyhee_r_bl_owyhee_dam  2006  906.850
2169  owyhee_r_bl_owyhee_dam  2008  345.819
2170  owyhee_r_bl_owyhee_dam  2010  297.684
2171  owyhee_r_bl_owyhee_dam  2012  117.728
2172  owyhee_r_bl_owyhee_dam  2014   69.818
2173  owyhee_r_bl_owyhee_dam  2016  213.150
2174  owyhee_r_bl_owyhee_dam  2018  118.743
2175  owyhee_r_bl_owyhee_dam  2020  180.786
2176  owyhee_r_bl_owyhee_dam  2022  154.332

In [35]:
metadata = pd.read_csv('./CSV/metadata.csv')

metadata

,site_id,season_start_month,season_end_month,elevation,latitude,longitude,drainage_area,usgs_id,usgs_name,nrcs_id,nrcs_name,rfc_id,rfc_name,rfc
0,hungry_horse_reservoir_inflow,4,7,3040.00,48.356630,-114.037620,1668.0,12362500.0,S F Flathead River nr Columbia Falls MT,12362500:MT:USGS,Hungry Horse Reservoir Inflow,HHWM8,SF Flathead - Hungry Horse Dam,NWRFC
1,snake_r_nr_heise,4,7,5015.00,43.612500,-111.660000,5752.0,13037500.0,Snake River NR Heise ID,13037500:ID:USGS,Snake R nr Heise,HEII1,Snake - Near Heise,NWRFC
2,pueblo_reservoir_inflow,4,7,4740.00,38.271670,-104.718030,4670.0,7099400.0,Arkansas River above Pueblo CO,07099400:CO:USGS,Pueblo Reservoir Inflow,PDAC2,Arkansas River Above Pueblo,ARBRFC
3,sweetwater_r_nr_alcova,4,7,5890.00,42.489960,-107.133940,2338.0,6639000.0,"Sweetwater River Near Alcova, WY",06639000:WY:USGS,Sweetwater R nr Alcova,NaN,NaN,NaN
4,missouri_r_at_toston,4,7,3906.00,46.146040,-111.420520,14641.0,6054500.0,Missouri River at Toston MT,06054500:MT:USGS,Missouri R at Toston,TOSM8,Missouri River at Toston,MBRFC
5,animas_r_at_durango,4,7,6502.00,37.279170,-107.880340,701.0,9361500.0,"Animas River at Durango, CO",09361500:CO:USGS,Animas R at Durango,DRGC2,Animas - Durango,CBRFC
6,yampa_r_nr_maybell,4,7,5900.00,40.502750,-108.033420,3383.0,9251000.0,"Yampa River Near Maybell, CO",09251000:CO:USGS,Yampa R nr Maybell,MBLC2,Yampa - Maybell Nr,CBRFC
7,libby_reservoir_inflow,4,7,2100.00,48.400790,-115.320720,8999.0,12301933.0,Kootenai River BL Libby Dam NR Libby MT,12301933:MT:USGS,Libby Reservoir Inflow,LYDM8,Kootenai - Libby Dam,NWRFC
8,boise_r_nr_boise,4,7,2827.00,43.527670,-116.059550,2686.0,13202000.0,Boise River NR Boise ID,13202000:ID:USGS,Boise R nr Boise,LUCI1,Boise - Lucky Peak Dam,NWRFC
9,green_r_bl_howard_a_hanson_dam,4,7,990.00,47.283710,-121.797890,221.0,12105900.0,"Green River Below Howard A Hanson Dam, WA",12105900:WA:USGS,Green R bl Howard A Hanson Dam,HHDW1,Green - Howard Hanson Dam,NWRFC
10,taylor_park_reservoir_inflow,4,7,9170.00,38.818330,-106.609200,254.0,9109000.0,"Taylor River Below Taylor Park Reservoir, CO",09109209:CO:USGS,Taylor Park Reservoir Inflow,TPIC2,Taylor - Taylor Park Reservoir,CBRFC
11,dillon_reservoir_inflow,4,7,8760.00,39.625540,-106.066410,334.0,9050700.0,"Blue River Below Dillon, CO",09050700:CO:USGS,Dillon Reservoir Inflow,DIRC2,Blue - Dillon Reservoir,CBRFC
12,ruedi_reservoir_inflow,4,7,7766.00,39.361390,-106.818610,223.0,9080190.0,"Ruedi Reservoir Near Basalt, CO",09080190:CO:USGS,Ruedi Reservoir Inflow,RURC2,"Frying Pan - Reudi Reservoir, Basalt, Nr",CBRFC
13,fontenelle_reservoir_inflow,4,7,6506.00,42.027780,-110.066670,4280.0,9211150.0,"Fontenelle Reservoir Near Fontenelle, WY",09211150:WY:USGS,Fontenelle Reservoir Inflow,GBRW4,"Green - Fontenelle Reservoir, Fontenelle, Nr",CBRFC
14,weber_r_nr_oakley,4,7,6640.00,40.737170,-111.247970,162.0,10128500.0,"Weber River Near Oakley, UT",10128500:UT:USGS,Weber R nr Oakley,OAWU1,"Weber - Oakley, Nr",CBRFC
15,san_joaquin_river_millerton_reservoir,4,7,296.55,36.984394,-119.724312,1676.0,11251000.0,San Joaquin R BL Friant CA,NaN,NaN,FRAC1,San Joaquin River - Millerton Reservoir,CNRFC
16,merced_river_yosemite_at_pohono_bridge,4,7,3882.00,37.716278,-119.665667,321.0,11266500.0,Merced R A Pohono Bridge NR Yosemite CA,NaN,NaN,POHC1,Merced River - Yosemite at Pohono Bridge,CNRFC
17,american_river_folsom_lake,4,7,239.00,38.704528,-121.164361,1863.0,11446220.0,American R BL Folsom Dam NR Folsom CA,NaN,NaN,FOLC1,American River - Folsom Lake,CNRFC
18,colville_r_at_kettle_falls,4,7,1400.00,48.594350,-118.062490,1007.0,12409000.0,"Colville R at Kettle Falls, WA",12409000:WA:USGS,Colville R at Kettle Falls,NaN,NaN,NaN
19,stehekin_r_at_stehekin,4,7,1099.00,48.329580,-120.691770,321.0,12451000.0,"Stehekin River at Stehekin, WA",12451000:WA:USGS,Stehekin R at Stehekin,STHW1,Stehekin - At Stehekin,NWRFC
20,detroit_lake_inflow,4,6,1094.00,44.752620,-122.298410,453.0,14181500.0,North Santiam River at Niagara OR,14181500:OR:USGS,Detroit Lake Inflow,DETO3,North Santiam - Detroit Dam,NWRFC
21,virgin_r_at_virtin,4,7,3500.00,37.204150,-113.180780,956.0,9406000.0,"Virgin River at Virgin, UT",09406000:UT:USGS,Virgin R at Virtin,VIRU1,Virgin - Virgin,CBRFC
22,skagit_ross_reservoir,4,7,1220.00,48.732171,-121.067614,NaN,NaN,NaN,NaN,NaN,RODW1,Skagit - Ross Reservoir,NWRFC
23,boysen_reservoir_inflow,4,7,4609.00,43.424960,-108.178990,7701.0,6259000.0,"Wind River Below Boysen Reservoir, WY",06259000:WY:USGS,Boysen Reservoir Inflow,SBDW4,Boysen Reservoir Inflow,MBRFC
24,pecos_r_nr_pecos,3,7,7503.00,35.708350,-105.682700,189.0,8378500.0,"Pecos River Near Pecos, NM",08378500:NM:USGS,Pecos R nr Pecos,PCON5,Pecos River Near Pecos,WGRFC
25,owyhee_r_bl_owyhee_dam,4,7,2344.00,43.654440,-117.255830,11160.0,13183000.0,Owyhee River Below Owyhee Dam,13183000:OR:USGS,Owyhee R bl Owyhee Dam,OWYO3,Owyhee - Owyhee Dam,NWRFC

In [36]:
submission = pd.read_csv('./CSV/submission_format.csv')

submission.head(4*12)

                          site_id  issue_date  volume_10  volume_50  volume_90
0   hungry_horse_reservoir_inflow  2005-01-01        0.0        0.0        0.0
1   hungry_horse_reservoir_inflow  2005-01-08        0.0        0.0        0.0
2   hungry_horse_reservoir_inflow  2005-01-15        0.0        0.0        0.0
3   hungry_horse_reservoir_inflow  2005-01-22        0.0        0.0        0.0
4   hungry_horse_reservoir_inflow  2005-02-01        0.0        0.0        0.0
5   hungry_horse_reservoir_inflow  2005-02-08        0.0        0.0        0.0
6   hungry_horse_reservoir_inflow  2005-02-15        0.0        0.0        0.0
7   hungry_horse_reservoir_inflow  2005-02-22        0.0        0.0        0.0
8   hungry_horse_reservoir_inflow  2005-03-01        0.0        0.0        0.0
9   hungry_horse_reservoir_inflow  2005-03-08        0.0        0.0        0.0
10  hungry_horse_reservoir_inflow  2005-03-15        0.0        0.0        0.0
11  hungry_horse_reservoir_inflow  2005-03-22        0.0        0.0        0.0
12  hungry_horse_reservoir_inflow  2005-04-01        0.0        0.0        0.0
13  hungry_horse_reservoir_inflow  2005-04-08        0.0        0.0        0.0
14  hungry_horse_reservoir_inflow  2005-04-15        0.0        0.0        0.0
15  hungry_horse_reservoir_inflow  2005-04-22        0.0        0.0        0.0
16  hungry_horse_reservoir_inflow  2005-05-01        0.0        0.0        0.0
17  hungry_horse_reservoir_inflow  2005-05-08        0.0        0.0        0.0
18  hungry_horse_reservoir_inflow  2005-05-15        0.0        0.0        0.0
19  hungry_horse_reservoir_inflow  2005-05-22        0.0        0.0        0.0
20  hungry_horse_reservoir_inflow  2005-06-01        0.0        0.0        0.0
21  hungry_horse_reservoir_inflow  2005-06-08        0.0        0.0        0.0
22  hungry_horse_reservoir_inflow  2005-06-15        0.0        0.0        0.0
23  hungry_horse_reservoir_inflow  2005-06-22        0.0        0.0        0.0
24  hungry_horse_reservoir_inflow  2005-07-01        0.0        0.0        0.0
25  hungry_horse_reservoir_inflow  2005-07-08        0.0        0.0        0.0
26  hungry_horse_reservoir_inflow  2005-07-15        0.0        0.0        0.0
27  hungry_horse_reservoir_inflow  2005-07-22        0.0        0.0        0.0
28               snake_r_nr_heise  2005-01-01        0.0        0.0        0.0
29               snake_r_nr_heise  2005-01-08        0.0        0.0        0.0
30               snake_r_nr_heise  2005-01-15        0.0        0.0        0.0
31               snake_r_nr_heise  2005-01-22        0.0        0.0        0.0
32               snake_r_nr_heise  2005-02-01        0.0        0.0        0.0
33               snake_r_nr_heise  2005-02-08        0.0        0.0        0.0
34               snake_r_nr_heise  2005-02-15        0.0        0.0        0.0
35               snake_r_nr_heise  2005-02-22        0.0        0.0        0.0
36               snake_r_nr_heise  2005-03-01        0.0        0.0        0.0
37               snake_r_nr_heise  2005-03-08        0.0        0.0        0.0
38               snake_r_nr_heise  2005-03-15        0.0        0.0        0.0
39               snake_r_nr_heise  2005-03-22        0.0        0.0        0.0
40               snake_r_nr_heise  2005-04-01        0.0        0.0        0.0
41               snake_r_nr_heise  2005-04-08        0.0        0.0        0.0
42               snake_r_nr_heise  2005-04-15        0.0        0.0        0.0
43               snake_r_nr_heise  2005-04-22        0.0        0.0        0.0
44               snake_r_nr_heise  2005-05-01        0.0        0.0        0.0
45               snake_r_nr_heise  2005-05-08        0.0        0.0        0.0
46               snake_r_nr_heise  2005-05-15        0.0        0.0        0.0
47               snake_r_nr_heise  2005-05-22        0.0        0.0        0.0

In [37]:
import geopandas as gpd

In [38]:
basins_layer = gpd.read_file('./GeoSpatial/geospatial.gpkg', layer='basins')

basins_layer.drop(columns=['name'], inplace=True)

basins_layer

,site_id,area,geometry
0,hungry_horse_reservoir_inflow,1681.780,"POLYGON ((-113.09701 47.24399, -113.09730 47.2..."
1,snake_r_nr_heise,5719.410,"MULTIPOLYGON (((-110.79196 44.40127, -110.7922..."
2,pueblo_reservoir_inflow,4615.460,"POLYGON ((-105.67340 38.15883, -105.67315 38.1..."
3,sweetwater_r_nr_alcova,2377.280,"POLYGON ((-107.32822 42.21621, -107.32903 42.2..."
4,missouri_r_at_toston,14676.200,"POLYGON ((-110.63001 46.30856, -110.63006 46.3..."
5,animas_r_at_durango,700.901,"POLYGON ((-107.87584 37.27614, -107.87759 37.2..."
6,yampa_r_nr_maybell,3381.680,"MULTIPOLYGON (((-107.02802 40.02615, -107.0277..."
7,libby_reservoir_inflow,9030.450,"MULTIPOLYGON (((-114.85817 48.50961, -114.8582..."
8,boise_r_nr_boise,2687.340,"MULTIPOLYGON (((-115.23528 44.09596, -115.2355..."
9,green_r_bl_howard_a_hanson_dam,221.234,"POLYGON ((-121.31474 47.13373, -121.31530 47.1..."
10,taylor_park_reservoir_inflow,254.415,"MULTIPOLYGON (((-106.74944 39.04268, -106.7499..."
11,dillon_reservoir_inflow,328.429,"POLYGON ((-106.04383 39.35748, -106.04564 39.3..."
12,ruedi_reservoir_inflow,223.740,"POLYGON ((-106.52087 39.15795, -106.52216 39.1..."
13,fontenelle_reservoir_inflow,4199.150,"POLYGON ((-110.06865 42.02568, -110.06944 42.0..."
14,weber_r_nr_oakley,162.429,"POLYGON ((-111.06529 40.67623, -111.06633 40.6..."
15,san_joaquin_river_millerton_reservoir,1886.720,"MULTIPOLYGON (((-120.44227 39.29433, -120.4423..."
16,merced_river_yosemite_at_pohono_bridge,321.858,"POLYGON ((-119.44368 37.86102, -119.44401 37.8..."
17,american_river_folsom_lake,1677.530,"MULTIPOLYGON (((-119.52661 37.04015, -119.5265..."
18,colville_r_at_kettle_falls,1086.250,"POLYGON ((-117.88747 48.70666, -117.88776 48.7..."
19,stehekin_r_at_stehekin,319.664,"POLYGON ((-120.93255 48.19748, -120.93284 48.1..."
20,detroit_lake_inflow,452.383,"POLYGON ((-121.85271 44.46766, -121.85379 44.4..."
21,virgin_r_at_virtin,948.039,"MULTIPOLYGON (((-112.73274 37.06034, -112.7327..."
22,skagit_ross_reservoir,800.749,"MULTIPOLYGON (((-120.98078 48.74358, -120.9810..."
23,boysen_reservoir_inflow,7706.580,"POLYGON ((-108.50590 42.46772, -108.50643 42.4..."
24,pecos_r_nr_pecos,171.839,"MULTIPOLYGON (((-105.50099 35.90638, -105.5007..."
25,owyhee_r_bl_owyhee_dam,11659.800,"POLYGON ((-118.19040 43.09658, -118.19034 43.0..."

In [39]:
sites_layer = gpd.read_file('./GeoSpatial/geospatial.gpkg', layer='sites')

sites_layer.rename(columns={'geometry': 'location'}, inplace=True)

sites_layer

,site_id,name,location
0,hungry_horse_reservoir_inflow,Hungry Horse Reservoir Inflow,POINT (-114.03786 48.35658)
1,snake_r_nr_heise,Snake River near Heise,POINT (-111.66000 43.61250)
2,pueblo_reservoir_inflow,Pueblo Reservoir Inflow,POINT (-104.71803 38.27167)
3,sweetwater_r_nr_alcova,Sweetwater River near Alcova,POINT (-107.13394 42.48996)
4,missouri_r_at_toston,Missouri River at Toston,POINT (-111.42028 46.14657)
5,animas_r_at_durango,Animas River at Durango,POINT (-107.88035 37.27917)
6,yampa_r_nr_maybell,Yampa River near Maybell,POINT (-108.03341 40.50275)
7,libby_reservoir_inflow,Libby Reservoir Inflow,POINT (-115.31872 48.40066)
8,boise_r_nr_boise,Boise River near Boise,POINT (-116.05955 43.52767)
9,green_r_bl_howard_a_hanson_dam,Green River below Howard Hanson Dam,POINT (-121.79789 47.28371)
10,taylor_park_reservoir_inflow,Taylor Park Reservoir Inflow,POINT (-106.60920 38.81833)
11,dillon_reservoir_inflow,Dillon Reservoir Inflow,POINT (-106.06641 39.62554)
12,ruedi_reservoir_inflow,Ruedi Reservoir Inflow,POINT (-106.81865 39.36387)
13,fontenelle_reservoir_inflow,Fontenelle Reservoir Inflow,POINT (-110.06667 42.02778)
14,weber_r_nr_oakley,Weber River near Oakley,POINT (-111.24796 40.73717)
15,san_joaquin_river_millerton_reservoir,San Joaquin River - Millerton Reservoir,POINT (-119.72431 36.98439)
16,merced_river_yosemite_at_pohono_bridge,Merced River - Yosemite at Pohono Bridge,POINT (-119.66567 37.71628)
17,american_river_folsom_lake,American River - Folsom Reservoir,POINT (-121.16436 38.70453)
18,colville_r_at_kettle_falls,Colville River at Kettle Falls,POINT (-118.06249 48.59435)
19,stehekin_r_at_stehekin,Stehekin River at Stehekin,POINT (-120.69177 48.32958)
20,detroit_lake_inflow,Detroit Lake Inflow,POINT (-122.29744 44.75378)
21,virgin_r_at_virtin,Virgin River at Virgin,POINT (-113.18078 37.20415)
22,skagit_ross_reservoir,Ross Reservoir Inflow,POINT (-121.06761 48.73217)
23,boysen_reservoir_inflow,Boysen Reservoir Inflow,POINT (-108.17899 43.42496)
24,pecos_r_nr_pecos,Pecos River near Pecos,POINT (-105.68270 35.70835)
25,owyhee_r_bl_owyhee_dam,Owyhee River below Owyhee Dam,POINT (-117.25583 43.65444)

In [40]:
cross_sectional_data = pd.merge(metadata, basins_layer, on='site_id')
cross_sectional_data = pd.merge(cross_sectional_data, sites_layer, on='site_id')

cross_sectional_data

,site_id,season_start_month,season_end_month,elevation,latitude,longitude,drainage_area,usgs_id,usgs_name,nrcs_id,nrcs_name,rfc_id,rfc_name,rfc,area,geometry,name,location
0,hungry_horse_reservoir_inflow,4,7,3040.00,48.356630,-114.037620,1668.0,12362500.0,S F Flathead River nr Columbia Falls MT,12362500:MT:USGS,Hungry Horse Reservoir Inflow,HHWM8,SF Flathead - Hungry Horse Dam,NWRFC,1681.780,"POLYGON ((-113.09701 47.24399, -113.09730 47.2...",Hungry Horse Reservoir Inflow,POINT (-114.03786 48.35658)
1,snake_r_nr_heise,4,7,5015.00,43.612500,-111.660000,5752.0,13037500.0,Snake River NR Heise ID,13037500:ID:USGS,Snake R nr Heise,HEII1,Snake - Near Heise,NWRFC,5719.410,"MULTIPOLYGON (((-110.79196 44.40127, -110.7922...",Snake River near Heise,POINT (-111.66000 43.61250)
2,pueblo_reservoir_inflow,4,7,4740.00,38.271670,-104.718030,4670.0,7099400.0,Arkansas River above Pueblo CO,07099400:CO:USGS,Pueblo Reservoir Inflow,PDAC2,Arkansas River Above Pueblo,ARBRFC,4615.460,"POLYGON ((-105.67340 38.15883, -105.67315 38.1...",Pueblo Reservoir Inflow,POINT (-104.71803 38.27167)
3,sweetwater_r_nr_alcova,4,7,5890.00,42.489960,-107.133940,2338.0,6639000.0,"Sweetwater River Near Alcova, WY",06639000:WY:USGS,Sweetwater R nr Alcova,NaN,NaN,NaN,2377.280,"POLYGON ((-107.32822 42.21621, -107.32903 42.2...",Sweetwater River near Alcova,POINT (-107.13394 42.48996)
4,missouri_r_at_toston,4,7,3906.00,46.146040,-111.420520,14641.0,6054500.0,Missouri River at Toston MT,06054500:MT:USGS,Missouri R at Toston,TOSM8,Missouri River at Toston,MBRFC,14676.200,"POLYGON ((-110.63001 46.30856, -110.63006 46.3...",Missouri River at Toston,POINT (-111.42028 46.14657)
5,animas_r_at_durango,4,7,6502.00,37.279170,-107.880340,701.0,9361500.0,"Animas River at Durango, CO",09361500:CO:USGS,Animas R at Durango,DRGC2,Animas - Durango,CBRFC,700.901,"POLYGON ((-107.87584 37.27614, -107.87759 37.2...",Animas River at Durango,POINT (-107.88035 37.27917)
6,yampa_r_nr_maybell,4,7,5900.00,40.502750,-108.033420,3383.0,9251000.0,"Yampa River Near Maybell, CO",09251000:CO:USGS,Yampa R nr Maybell,MBLC2,Yampa - Maybell Nr,CBRFC,3381.680,"MULTIPOLYGON (((-107.02802 40.02615, -107.0277...",Yampa River near Maybell,POINT (-108.03341 40.50275)
7,libby_reservoir_inflow,4,7,2100.00,48.400790,-115.320720,8999.0,12301933.0,Kootenai River BL Libby Dam NR Libby MT,12301933:MT:USGS,Libby Reservoir Inflow,LYDM8,Kootenai - Libby Dam,NWRFC,9030.450,"MULTIPOLYGON (((-114.85817 48.50961, -114.8582...",Libby Reservoir Inflow,POINT (-115.31872 48.40066)
8,boise_r_nr_boise,4,7,2827.00,43.527670,-116.059550,2686.0,13202000.0,Boise River NR Boise ID,13202000:ID:USGS,Boise R nr Boise,LUCI1,Boise - Lucky Peak Dam,NWRFC,2687.340,"MULTIPOLYGON (((-115.23528 44.09596, -115.2355...",Boise River near Boise,POINT (-116.05955 43.52767)
9,green_r_bl_howard_a_hanson_dam,4,7,990.00,47.283710,-121.797890,221.0,12105900.0,"Green River Below Howard A Hanson Dam, WA",12105900:WA:USGS,Green R bl Howard A Hanson Dam,HHDW1,Green - Howard Hanson Dam,NWRFC,221.234,"POLYGON ((-121.31474 47.13373, -121.31530 47.1...",Green River below Howard Hanson Dam,POINT (-121.79789 47.28371)
10,taylor_park_reservoir_inflow,4,7,9170.00,38.818330,-106.609200,254.0,9109000.0,"Taylor River Below Taylor Park Reservoir, CO",09109209:CO:USGS,Taylor Park Reservoir Inflow,TPIC2,Taylor - Taylor Park Reservoir,CBRFC,254.415,"MULTIPOLYGON (((-106.74944 39.04268, -106.7499...",Taylor Park Reservoir Inflow,POINT (-106.60920 38.81833)
11,dillon_reservoir_inflow,4,7,8760.00,39.625540,-106.066410,334.0,9050700.0,"Blue River Below Dillon, CO",09050700:CO:USGS,Dillon Reservoir Inflow,DIRC2,Blue - Dillon Reservoir,CBRFC,328.429,"POLYGON ((-106.04383 39.35748, -106.04564 39.3...",Dillon Reservoir Inflow,POINT (-106.06641 39.62554)
12,ruedi_reservoir_inflow,4,7,7766.00,39.361390,-106.818610,223.0,9080190.0,"Ruedi Reservoir Near Basalt, CO",09080190:CO:USGS,Ruedi Reservoir Inflow,RURC2,"Frying Pan - Reudi Reservoir, Basalt, Nr",CBRFC,223.740,"POLYGON ((-106.52087 39.15795, -106.52216 39.1...",Ruedi Reservoir Inflow,POINT (-106.81865 39.36387)
13,fontenelle_reservoir_inflow,4,7,6506.00,42.027780,-110.066670,4280.0,9211150.0,"Fontenelle Reservoir Near Fontenelle, WY",09211150:WY:USGS,Fontenelle Reservoir Inflow,GBRW4,"Green - Fontenelle Reservoir, Fontenelle, Nr",CBRFC,4199.150,"POLYGON ((-110.06865 42.02568, -110.06944 42.0...",Fontenelle Reservoir Inflow,POINT (-110.06667 42.02778)
14,weber_r_nr_oakley,4,7,6640.00,40.737170,-111.247970,162.0,10128500.0,"Weber River Near Oakley, UT",10128500:UT:USGS,Weber R nr Oakley,OAWU1,"Weber - Oakley, Nr",CBRFC,162.429,"POLYGON ((-111.06529 40.67623, -111.06633 40.6...",Weber River near Oakley,POINT (-111.24796 40.73717)
15,san_joaquin_river_millerton_reservoir,4,7,296.55,36.984394,-119.724312,1676.0,11251000.0,San Joaquin R BL Friant CA,NaN,NaN,FRAC1,San Joaquin River - Millerton Reservoir,CNRFC,1886.720,"MULTIPOLYGON (((-120.44227 39.29433, -120.4423...",San Joaquin River - Millerton Reservoir,POINT (-119.72431 36.98439)
16,merced_river_yosemite_at_pohono_bridge,4,7,3882.00,37.716278,-119.665667,321.0,11266500.0,Merced R A Pohono Bridge NR Yosemite CA,NaN,NaN,POHC1,Merced River - Yosemite at Pohono Bridge,CNRFC,321.858,"POLYGON ((-119.44368 37.86102, -119.44401 37.8...",Merced River - Yosemite at Pohono Bridge,POINT (-119.66567 37.71628)
17,american_river_folsom_lake,4,7,239.00,38.704528,-121.164361,1863.0,11446220.0,American R BL Folsom Dam NR Folsom CA,NaN,NaN,FOLC1,American River - Folsom Lake,CNRFC,1677.530,"MULTIPOLYGON (((-119.52661 37.04015, -119.5265...",American River - Folsom Reservoir,POINT (-121.16436 38.70453)
18,colville_r_at_kettle_falls,4,7,1400.00,48.594350,-118.062490,1007.0,12409000.0,"Colville R at Kettle Falls, WA",12409000:WA:USGS,Colville R at Kettle Falls,NaN,NaN,NaN,1086.250,"POLYGON ((-117.88747 48.70666, -117.88776 48.7...",Colville River at Kettle Falls,POINT (-118.06249 48.59435)
19,stehekin_r_at_stehekin,4,7,1099.00,48.329580,-120.691770,321.0,12451000.0,"Stehekin River at Stehekin, WA",12451000:WA:USGS,Stehekin R at Stehekin,STHW1,Stehekin - At Stehekin,NWRFC,319.664,"POLYGON ((-120.93255 48.19748, -120.93284 48.1...",Stehekin River at Stehekin,POINT (-120.69177 48.32958)
20,detroit_lake_inflow,4,6,1094.00,44.752620,-122.298410,453.0,14181500.0,North Santiam River at Niagara OR,14181500:OR:USGS,Detroit Lake Inflow,DETO3,North Santiam - Detroit Dam,NWRFC,452.383,"POLYGON ((-121.85271 44.46766, -121.85379 44.4...",Detroit Lake Inflow,POINT (-122.29744 44.75378)
21,virgin_r_at_virtin,4,7,3500.00,37.204150,-113.180780,956.0,9406000.0,"Virgin River at Virgin, UT",09406000:UT:USGS,Virgin R at Virtin,VIRU1,Virgin - Virgin,CBRFC,948.039,"MULTIPOLYGON (((-112.73274 37.06034, -112.7327...",Virgin River at Virgin,POINT (-113.18078 37.20415)
22,skagit_ross_reservoir,4,7,1220.00,48.732171,-121.067614,NaN,NaN,NaN,NaN,NaN,RODW1,Skagit - Ross Reservoir,NWRFC,800.749,"MULTIPOLYGON (((-120.98078 48.74358, -120.9810...",Ross Reservoir Inflow,POINT (-121.06761 48.73217)
23,boysen_reservoir_inflow,4,7,4609.00,43.424960,-108.178990,7701.0,6259000.0,"Wind River Below Boysen Reservoir, WY",06259000:WY:USGS,Boysen Reservoir Inflow,SBDW4,Boysen Reservoir Inflow,MBRFC,7706.580,"POLYGON ((-108.50590 42.46772, -108.50643 42.4...",Boysen Reservoir Inflow,POINT (-108.17899 43.42496)
24,pecos_r_nr_pecos,3,7,7503.00,35.708350,-105.682700,189.0,8378500.0,"Pecos River Near Pecos, NM",08378500:NM:USGS,Pecos R nr Pecos,PCON5,Pecos River Near Pecos,WGRFC,171.839,"MULTIPOLYGON (((-105.50099 35.90638, -105.5007...",Pecos River near Pecos,POINT (-105.68270 35.70835)
25,owyhee_r_bl_owyhee_dam,4,7,2344.00,43.654440,-117.255830,11160.0,13183000.0,Owyhee River Below Owyhee Dam,13183000:OR:USGS,Owyhee R bl Owyhee Dam,OWYO3,Owyhee - Owyhee Dam,NWRFC,11659.800,"POLYGON ((-118.19040 43.09658, -118.19034 43.0...",Owyhee River below Owyhee Dam,POINT (-117.25583 43.65444)

In [41]:
cross_sectional_data.to_csv('./CSV/cross-sectional-data.csv')